[env]
platform = atmelavr
board = uno
framework = arduino
build_flags = -std=gnu++17
build_unflags = -std=gnu++11

[env:task1]
build_src_filter = -<*> +<task1/>

[env:task2]
build_src_filter = -<*> +<task2/>

[env:task3]
build_src_filter = -<*> +<task3/>
